import QtQuick
import QtQuick.Layouts
Item{
	property string name:''
	property string user:''
	property string song:''
	property string artist:''
	property bool play:false
	id:xRoot
	Layout.fillWidth:true
	height:xColumn.height
	Rectangle{
		anchors.fill:parent
		color:'#33000000'
		visible:!song||play
		LRShadow{}
	}
	LRLink{
		id:xLink
		content:xRoot.user
		href:'https://www.last.fm/user/'+encodeURIComponent(xRoot.user)
	}
	ColumnLayout{
		id:xColumn
		spacing:5
		width:parent.width
		opacity:xLink.pressed?0.5:1
		RowLayout{
			Layout.rightMargin:15
			Layout.leftMargin:15
			Layout.fillWidth:true
			Layout.preferredHeight:54
			spacing:10
			LRCover{
				id:pfp
				base:'user_m'
			}
			ColumnLayout{
				Layout.fillWidth:true
				spacing:2
				LRElide{
					content:name?name:'@'+user
					size:'h3'
				}
				LRElide{
					visible:name&&user
					content:'@'+user
					alpha:0.81
				}
			}
			LRIcon{
				res:'link_web'
				size:14
			}
		}
		RowLayout{
			Layout.rightMargin:15
			Layout.leftMargin:15
			Layout.fillWidth:true
			visible:song
			spacing:10
			LRIcon{
				Layout.alignment:Qt.AlignTop
				visible:!play
				res:'clock_s'
				size:18
			}
			LRPlaying{
				Layout.alignment:Qt.AlignTop
				pause:!play
				visible:play
			}
			ColumnLayout{
				Layout.alignment:Qt.AlignTop
				Layout.bottomMargin:10
				spacing:1
				LRElide{
					LRLink{}
					content:song
					size:"h3"
				}
				LRElide{
					LRLink{}
					visible:artist
					content:artist
					alpha:0.81
				}
			}
		}
	}
}