pyinstaller app.spec --noconfirm || exit
rm "dist/LastRedux.app/Contents/MacOS/QtWebSockets"
rm "dist/LastRedux.app/Contents/MacOS/QtGamepad"
rm "dist/LastRedux.app/Contents/MacOS/QtQuick3DAssetImport"
rm "dist/LastRedux.app/Contents/MacOS/QtBluetooth"
rm "dist/LastRedux.app/Contents/MacOS/QtWebView"
rm "dist/LastRedux.app/Contents/MacOS/Qt3DCore"
rm "dist/LastRedux.app/Contents/MacOS/QtQuick3D"
rm "dist/LastRedux.app/Contents/MacOS/QtQuickShapes"
rm "dist/LastRedux.app/Contents/MacOS/QtSvg"
rm "dist/LastRedux.app/Contents/MacOS/Qt3DInput"
rm "dist/LastRedux.app/Contents/MacOS/QtQuickTest"
rm "dist/LastRedux.app/Contents/MacOS/QtRemoteObjects"
rm "dist/LastRedux.app/Contents/MacOS/QtPurchasing"
rm "dist/LastRedux.app/Contents/MacOS/QtSensors"
rm "dist/LastRedux.app/Contents/MacOS/QtMultimediaQuick"
rm "dist/LastRedux.app/Contents/MacOS/QtPdf"
rm "dist/LastRedux.app/Contents/MacOS/QtQuick3DUtils"
rm "dist/LastRedux.app/Contents/MacOS/Qt3DQuick"
rm "dist/LastRedux.app/Contents/MacOS/Qt3DQuickExtras"
rm "dist/LastRedux.app/Contents/MacOS/Qt3DLogic"
rm "dist/LastRedux.app/Contents/MacOS/Qt3DExtras"
rm "dist/LastRedux.app/Contents/MacOS/QtBodymovin"
rm "dist/LastRedux.app/Contents/MacOS/QtQuickParticles"
rm "dist/LastRedux.app/Contents/MacOS/Qt3DQuickAnimation"
rm "dist/LastRedux.app/Contents/MacOS/QtCharts"
rm "dist/LastRedux.app/Contents/MacOS/Qt3DQuickScene2D"
rm "dist/LastRedux.app/Contents/MacOS/QtNfc"
rm "dist/LastRedux.app/Contents/MacOS/QtVirtualKeyboard"
rm "dist/LastRedux.app/Contents/MacOS/Qt3DAnimation"
rm "dist/LastRedux.app/Contents/MacOS/QtWebEngine"
rm "dist/LastRedux.app/Contents/MacOS/QtWebChannel"
rm "dist/LastRedux.app/Contents/MacOS/QtDataVisualization"
rm "dist/LastRedux.app/Contents/MacOS/QtMultimedia"
rm "dist/LastRedux.app/Contents/MacOS/Qt3DQuickInput"
rm "dist/LastRedux.app/Contents/MacOS/QtPositioningQuick"
rm "dist/LastRedux.app/Contents/MacOS/QtLocation"
rm "dist/LastRedux.app/Contents/MacOS/QtQuick3DRender"
rm "dist/LastRedux.app/Contents/MacOS/QtPositioning"
rm "dist/LastRedux.app/Contents/MacOS/QtXmlPatterns"
rm "dist/LastRedux.app/Contents/MacOS/QtWebEngineCore"
rm "dist/LastRedux.app/Contents/MacOS/QtQuick3DRuntimeRender"
rm "dist/LastRedux.app/Contents/MacOS/Qt3DRender"
rm "dist/LastRedux.app/Contents/MacOS/QtScxml"
rm "dist/LastRedux.app/Contents/MacOS/QtTest"
rm "dist/LastRedux.app/Contents/MacOS/Qt3DQuickRender"
rm "dist/LastRedux.app/Contents/MacOS/PySide2/plugins/platforms/libqminimal.dylib"
rm "dist/LastRedux.app/Contents/MacOS/PySide2/plugins/platforms/libqoffscreen.dylib"
rm "dist/LastRedux.app/Contents/MacOS/PySide2/plugins/platforms/libqwebgl.dylib"
rm "dist/LastRedux.app/Contents/MacOS/PySide2/plugins/platformthemes/libqxdgdesktopportal.dylib"
rm -rf "dist/LastRedux.app/Contents/MacOS/PySide2/qml/QtWebSockets"
rm -rf "dist/LastRedux.app/Contents/MacOS/PySide2/qml/QtGamepad"
rm -rf "dist/LastRedux.app/Contents/MacOS/PySide2/qml/QtBluetooth"
rm -rf "dist/LastRedux.app/Contents/MacOS/PySide2/qml/QtWebView"
rm -rf "dist/LastRedux.app/Contents/MacOS/PySide2/qml/QtQuick3D"
rm -rf "dist/LastRedux.app/Contents/MacOS/PySide2/qml/QtRemoteObjects"
rm -rf "dist/LastRedux.app/Contents/MacOS/PySide2/qml/QtPurchasing"
rm -rf "dist/LastRedux.app/Contents/MacOS/PySide2/qml/QtSensors"
rm -rf "dist/LastRedux.app/Contents/MacOS/PySide2/qml/QtCharts"
rm -rf "dist/LastRedux.app/Contents/MacOS/PySide2/qml/QtNfc"
rm -rf "dist/LastRedux.app/Contents/MacOS/PySide2/qml/QtWebEngine"
rm -rf "dist/LastRedux.app/Contents/MacOS/PySide2/qml/QtWebChannel"
rm -rf "dist/LastRedux.app/Contents/MacOS/PySide2/qml/QtDataVisualization"
rm -rf "dist/LastRedux.app/Contents/MacOS/PySide2/qml/QtMultimedia"
rm -rf "dist/LastRedux.app/Contents/MacOS/PySide2/qml/QtLocation"
rm -rf "dist/LastRedux.app/Contents/MacOS/PySide2/qml/Qt3D"
rm -rf "dist/LastRedux.app/Contents/MacOS/PySide2/qml/QtPositioning"
rm -rf "dist/LastRedux.app/Contents/MacOS/PySide2/qml/QtAudioEngine"
rm -rf "dist/LastRedux.app/Contents/MacOS/PySide2/qml/QtScxml"
rm -rf "dist/LastRedux.app/Contents/MacOS/PySide2/qml/QtTest"
rm -rf "dist/app"
rm -rf "build"
